$background = rgb(090B09)
$foreground = rgb(CFCDCA)
$color0 = rgb(090B09)
$color1 = rgb(282B22)
$color2 = rgb(272D25)
$color3 = rgb(463020)
$color4 = rgb(73381D)
$color5 = rgb(4E4D45)
$color6 = rgb(58554D)
$color7 = rgb(B2B0AB)
$color8 = rgb(7C7B77)
$color9 = rgb(36392D)
$color10 = rgb(333C32)
$color11 = rgb(5D402A)
$color12 = rgb(994B26)
$color13 = rgb(68665C)
$color14 = rgb(757167)
$color15 = rgb(B2B0AB)
